name: .NET

on:
  push:
    branches: [ master, actions ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      working-directory: ./project-2
      run: dotnet restore AllianceEngine.sln
    - name: Build
      working-directory: ./project-2
      run: dotnet build --no-restore AllianceEngine.sln
